
  Performance statistics for DSP solver: icalls =      1

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           86670
     no. of nonzeroes in lower triangle of a =         5247666
     no. of nonzeroes in the factor l        =        30626146
     ratio of nonzeroes in factor (min/max)  =          0.5141
     number of super nodes                   =            2104
     maximum order of a front matrix         =             810
     maximum size of a front matrix          =          328455
     maximum size of a front trapezoid       =          182385
     no. of floating point ops for factor    =      1.2598D+10
     no. of floating point ops for solve     =      1.1480D+08
     ratio of flops for factor (min/max)     =          0.5266
     ratio of allocated memory (max/min)     =          1.3766
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =              32
     number of threads per process used      =               1
     number of cores used                    =              32
     time (cpu & wall) for structure input   =        0.015625        0.010320
     time (cpu & wall) for ordering          =        0.046875        0.041781
     time (cpu & wall) for other matrix prep =        0.015625        0.024114
     time (cpu & wall) for value input       =        0.015625        0.015958
     time (cpu & wall) for matrix distrib.   =        0.140625        0.137450
     time (cpu & wall) for numeric factor    =        0.171875        0.175916
     computational rate (gflops) for factor  =       73.298059       71.614234
     time (cpu & wall) for numeric solve     =        0.031250        0.030358
     computational rate (gflops) for solve   =        3.673707        3.781701
     effective I/O rate (GB/sec) for solve   =       13.686712       14.089051

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         32768.        0. MB         27545.        0. MB
                95-   1         32768.        0. MB         27584.        0. MB
                95-   2         32768.        0. MB         28843.        0. MB
                95-   3         32768.        0. MB         28196.        0. MB
                95-   4         32768.        0. MB         27624.        0. MB
                95-   5         32768.        0. MB         27069.        0. MB
                95-   6         32768.        0. MB         29168.        0. MB
                95-   7         32768.        0. MB         27318.        0. MB
                95-   8         32768.        0. MB         29963.        0. MB
                95-   9         32768.        0. MB         29272.        0. MB
                95-  10         32768.        0. MB         27512.        0. MB
                95-  11         32768.        0. MB         26610.        0. MB
                95-  12         32768.        0. MB         27724.        0. MB
                95-  13         32768.        0. MB         27346.        0. MB
                95-  14         32768.        0. MB         26942.        0. MB
                95-  15         32768.        0. MB         26729.        0. MB
                95-  16         32768.        0. MB         28807.        0. MB
                95-  17         32768.        0. MB         27300.        0. MB
                95-  18         32768.        0. MB         26532.        0. MB
                95-  19         32768.        0. MB         26512.        0. MB
                95-  20         65536.        0. MB         34949.        0. MB
                95-  21         32768.        0. MB         22363.        0. MB
                95-  22         32768.        0. MB         27954.        0. MB
                95-  23         32768.        0. MB         27859.        0. MB
                95-  24         32768.        0. MB         27866.        0. MB
                95-  25         32768.        0. MB         27225.        0. MB
                95-  26         32768.        0. MB         29451.        0. MB
                95-  27         32768.        0. MB         26718.        0. MB
                95-  28         32768.        0. MB         26634.        0. MB
                95-  29         32768.        0. MB         26736.        0. MB
                95-  30         32768.        0. MB         26785.        0. MB
                95-  31         32768.        0. MB         26187.        0. MB

                -------     ----------     --------     ----------     --------
                Totals:       1081344.        8. MB        885323.        7. MB


  Solver Memory allocated on core    0       =       27.160 MB
  Solver Memory allocated on core    1       =       25.761 MB
  Solver Memory allocated on core    2       =       27.141 MB
  Solver Memory allocated on core    3       =       26.371 MB
  Solver Memory allocated on core    4       =       26.297 MB
  Solver Memory allocated on core    5       =       25.326 MB
  Solver Memory allocated on core    6       =       26.736 MB
  Solver Memory allocated on core    7       =       24.965 MB
  Solver Memory allocated on core    8       =       27.059 MB
  Solver Memory allocated on core    9       =       26.056 MB
  Solver Memory allocated on core   10       =       25.346 MB
  Solver Memory allocated on core   11       =       24.515 MB
  Solver Memory allocated on core   12       =       25.851 MB
  Solver Memory allocated on core   13       =       25.431 MB
  Solver Memory allocated on core   14       =       25.475 MB
  Solver Memory allocated on core   15       =       24.524 MB
  Solver Memory allocated on core   16       =       26.103 MB
  Solver Memory allocated on core   17       =       24.434 MB
  Solver Memory allocated on core   18       =       24.333 MB
  Solver Memory allocated on core   19       =       23.136 MB
  Solver Memory allocated on core   20       =       27.586 MB
  Solver Memory allocated on core   21       =       20.039 MB
  Solver Memory allocated on core   22       =       23.877 MB
  Solver Memory allocated on core   23       =       23.401 MB
  Solver Memory allocated on core   24       =       25.723 MB
  Solver Memory allocated on core   25       =       24.366 MB
  Solver Memory allocated on core   26       =       25.811 MB
  Solver Memory allocated on core   27       =       23.691 MB
  Solver Memory allocated on core   28       =       24.307 MB
  Solver Memory allocated on core   29       =       23.979 MB
  Solver Memory allocated on core   30       =       23.837 MB
  Solver Memory allocated on core   31       =       23.385 MB
  Total Solver Memory allocated by all cores =      802.022 MB

