-- Refined two-subtask optimization plan for t2_ tables.
-- Run after `t2_rule_fields_upgrade.sql`.
-- The layout task keeps executable-rule fields reserved for future algorithm integration.

SET NAMES utf8mb4;

UPDATE t2_design_objective_catalog
SET status = '1',
    update_by = 'admin',
    update_time = SYSDATE()
WHERE item_code IN (
  'STR_SPACE_SUPPORT_MAX',
  'STR_PIPE_CLEARANCE',
  'HYD_PRESSURE_DROP_MIN',
  'HYD_CLAMP_VALID',
  'HYD_PRESSURE_VELOCITY_INPUT',
  'HYD_VALVE_CLOSE_TIME',
  'LAY_COMPACTNESS_MAX',
  'LAY_DOOR_ENVELOPE_AVOID',
  'LAY_HYDRAULIC_PIPE_FIXED',
  'AERO_DOOR_GAP_CLEARANCE',
  'MFG_MAINTENANCE_ACCESS_MAX',
  'MFG_BEND_ANGLE_RANGE',
  'MFG_WALL_THICKNESS_LIMIT'
);

INSERT INTO t2_design_objective_catalog
  (discipline, discipline_name, item_type, item_code, item_name, direction,
   default_weight, default_limit_value, unit, sort_order, status, remark,
   rule_type, rule_expression, target_field, reference_field, operator_code,
   threshold_value, execute_mode, rule_payload, create_by, create_time)
VALUES
  ('hydraulic', '液压工程师', 'objective', 'HYD_STRESS_MIN', '最大等效应力最小', 'min',
   50, '', 'MPa', 10, '0', '液压弯管抗冲击优化核心目标',
   'objective_metric', 'min(maxEquivalentStress)', 'maxEquivalentStress', '', 'minimize',
   '', 'reserved', '', 'admin', SYSDATE()),
  ('hydraulic', '液压工程师', 'objective', 'HYD_DEFORMATION_MIN', '最大变形量最小', 'min',
   50, '', 'mm', 20, '0', '液压弯管抗冲击优化核心目标',
   'objective_metric', 'min(maxDeformation)', 'maxDeformation', '', 'minimize',
   '', 'reserved', '', 'admin', SYSDATE()),
  ('hydraulic', '液压工程师', 'constraint', 'HYD_STRESS_LIMIT', '最大等效应力不超过许用应力', '<=',
   50, '', 'MPa', 30, '0', '后续由仿真或代理模型返回应力值后执行',
   'strength_check', 'maxEquivalentStress <= allowableStress', 'maxEquivalentStress', 'allowableStress', 'less_equal',
   '', 'reserved', '', 'admin', SYSDATE()),
  ('hydraulic', '液压工程师', 'constraint', 'HYD_DEFORMATION_LIMIT', '最大变形量不超过允许变形', '<=',
   50, '', 'mm', 40, '0', '后续由仿真或代理模型返回变形值后执行',
   'deformation_check', 'maxDeformation <= allowableDeformation', 'maxDeformation', 'allowableDeformation', 'less_equal',
   '', 'reserved', '', 'admin', SYSDATE()),
  ('hydraulic', '液压工程师', 'constraint', 'HYD_MIN_BEND_RADIUS', '液压管弯曲半径不小于下限', '>=',
   50, '20', 'mm', 50, '0', '当前可按变量边界执行',
   'radius_check', 'PIPE_BEND_RADIUS >= minPipeBendRadius', 'PIPE_BEND_RADIUS', 'minPipeBendRadius', 'greater_equal',
   '20', 'reserved', '', 'admin', SYSDATE()),

  ('layout', '布局工程师', 'objective', 'LAY_INTERFERENCE_RISK_MIN', '线缆与液压管干涉风险最小', 'min',
   50, '', 'risk', 60, '0', '布局算法接入前先保留指标字段',
   'objective_metric', 'min(interferenceRisk)', 'interferenceRisk', '', 'minimize',
   '', 'reserved', '', 'admin', SYSDATE()),
  ('layout', '布局工程师', 'objective', 'LAY_CABLE_LENGTH_MIN', '线缆路径长度最小', 'min',
   50, '', 'm', 70, '0', '布局算法接入前先保留指标字段',
   'objective_metric', 'min(cablePathLength)', 'cablePathLength', '', 'minimize',
   '', 'reserved', '', 'admin', SYSDATE()),
  ('layout', '布局工程师', 'objective', 'LAY_MAINTAINABILITY_MAX', '维护可达性最大', 'max',
   50, '', 'score', 80, '0', '布局算法接入前先保留指标字段',
   'objective_metric', 'max(maintainabilityScore)', 'maintainabilityScore', '', 'maximize',
   '', 'reserved', '', 'admin', SYSDATE()),
  ('layout', '布局工程师', 'constraint', 'LAY_PIPE_CLEARANCE_LIMIT', '线缆与液压管保持安全间距', '>=',
   50, '40', 'mm', 90, '0', '可执行为最小距离校核',
   'clearance_check', 'minCablePipeClearance >= CABLE_PIPE_CLEARANCE', 'minCablePipeClearance', 'CABLE_PIPE_CLEARANCE', 'greater_equal',
   '40', 'reserved', '', 'admin', SYSDATE()),
  ('layout', '布局工程师', 'constraint', 'LAY_FORBIDDEN_ZONE_AVOID', '线缆不得穿越结构禁布区域', 'avoid',
   50, '', '', 100, '0', '可执行为路径与禁布区域的几何相交校核',
   'geometry_intersection', 'intersect(cableRouteGeometry, structureForbiddenZones) = false', 'cableRouteGeometry', 'structureForbiddenZones', 'none_intersect',
   '', 'reserved', '', 'admin', SYSDATE()),
  ('layout', '布局工程师', 'constraint', 'LAY_CABLE_BEND_RADIUS_LIMIT', '线缆弯曲半径满足要求', '>=',
   50, '50', 'mm', 110, '0', '可执行为弯曲半径下限校核',
   'radius_check', 'actualCableBendRadius >= CABLE_BEND_RADIUS', 'actualCableBendRadius', 'CABLE_BEND_RADIUS', 'greater_equal',
   '50', 'reserved', '', 'admin', SYSDATE()),
  ('layout', '布局工程师', 'constraint', 'LAY_CLAMP_SPACING_LIMIT', '线夹间距不超过上限', '<=',
   50, '250', 'mm', 120, '0', '可执行为线夹间距上限校核',
   'spacing_check', 'actualClampSpacing <= CLAMP_SPACING', 'actualClampSpacing', 'CLAMP_SPACING', 'less_equal',
   '250', 'reserved', '', 'admin', SYSDATE()),
  ('layout', '布局工程师', 'constraint', 'LAY_SERVICE_MARGIN_LIMIT', '检修空间满足要求', '>=',
   50, '30', 'mm', 130, '0', '可执行为检修空间下限校核',
   'clearance_check', 'actualServiceMargin >= SERVICE_MARGIN', 'actualServiceMargin', 'SERVICE_MARGIN', 'greater_equal',
   '30', 'reserved', '', 'admin', SYSDATE()),

  ('structure', '结构工程师', 'objective', 'STR_DEFORMATION_RISK_MIN', '管线变形碰撞风险最小', 'min',
   50, '', 'risk', 140, '0', '结构侧保留与管线变形相关的核心目标',
   'objective_metric', 'min(deformationCollisionRisk)', 'deformationCollisionRisk', '', 'minimize',
   '', 'reserved', '', 'admin', SYSDATE()),
  ('structure', '结构工程师', 'constraint', 'STR_FORBIDDEN_ZONE', '结构禁布区域不可穿越', 'avoid',
   50, '', '', 150, '0', '可执行为路径与结构禁布区域几何相交校核',
   'geometry_intersection', 'intersect(routeGeometry, structureForbiddenZones) = false', 'routeGeometry', 'structureForbiddenZones', 'none_intersect',
   '', 'reserved', '', 'admin', SYSDATE()),
  ('structure', '结构工程师', 'constraint', 'STR_INTERFACE_FIXED', '铰链、锁机构、作动器接口位置不可更改', 'fixed',
   50, '', '', 160, '0', '可执行为关键接口点与基准点一致性校核',
   'boundary_lock', 'interfacePoints = baselineInterfacePoints', 'interfacePoints', 'baselineInterfacePoints', 'equal',
   '', 'reserved', '', 'admin', SYSDATE()),
  ('structure', '结构工程师', 'constraint', 'STR_CLAMP_SUPPORT_VALID', '卡箍支撑点结构强度满足要求', 'meet',
   50, '', '', 170, '0', '可执行为支撑点强度校核',
   'strength_check', 'clampSupportStrength >= requiredSupportStrength', 'clampSupportStrength', 'requiredSupportStrength', 'pass',
   '', 'reserved', '', 'admin', SYSDATE()),

  ('aero', '气动工程师', 'objective', 'AERO_ENVELOPE_IMPACT_MIN', '对舱门外形包络影响最小', 'min',
   50, '', 'score', 180, '0', '气动侧仅保留包络影响核心项',
   'objective_metric', 'min(envelopeImpactScore)', 'envelopeImpactScore', '', 'minimize',
   '', 'reserved', '', 'admin', SYSDATE()),
  ('aero', '气动工程师', 'constraint', 'AERO_OUTER_ENVELOPE', '管线与附件不得超出舱门外形包络', '<=',
   50, '', 'mm', 190, '0', '可执行为包络内外关系校核',
   'envelope_check', 'routeEnvelope inside doorOuterEnvelope', 'routeEnvelope', 'doorOuterEnvelope', 'inside_or_equal',
   '', 'reserved', '', 'admin', SYSDATE()),

  ('manufacturing', '制造工程师', 'objective', 'MFG_PROCESS_COMPLEXITY_MIN', '管线制造加工复杂度最小', 'min',
   50, '', 'score', 200, '0', '制造侧保留加工复杂度目标',
   'objective_metric', 'min(processComplexityScore)', 'processComplexityScore', '', 'minimize',
   '', 'reserved', '', 'admin', SYSDATE()),
  ('manufacturing', '制造工程师', 'objective', 'MFG_ASSEMBLY_EFFICIENCY_MAX', '装配效率最大', 'max',
   50, '', 'score', 210, '0', '制造侧保留装配效率目标',
   'objective_metric', 'max(assemblyEfficiencyScore)', 'assemblyEfficiencyScore', '', 'maximize',
   '', 'reserved', '', 'admin', SYSDATE()),
  ('manufacturing', '制造工程师', 'constraint', 'MFG_BEND_RADIUS_LIMIT', '弯曲半径满足制造下限', '>=',
   50, '20', 'mm', 220, '0', '可执行为制造弯曲半径下限校核',
   'radius_check', 'bendRadius >= manufacturingMinBendRadius', 'bendRadius', 'manufacturingMinBendRadius', 'greater_equal',
   '20', 'reserved', '', 'admin', SYSDATE()),
  ('manufacturing', '制造工程师', 'constraint', 'MFG_CLAMP_INSTALLABLE', '管夹/线夹可安装', 'meet',
   50, '', '', 230, '0', '可执行为安装空间/孔位可用性校核',
   'installability_check', 'clampInstallability = pass', 'clampInstallability', '', 'pass',
   '', 'reserved', '', 'admin', SYSDATE()),
  ('manufacturing', '制造工程师', 'constraint', 'MFG_TOOL_ACCESS', '工具操作空间满足要求', 'meet',
   50, '', '', 240, '0', '可执行为工具可达性校核',
   'accessibility_check', 'toolAccessStatus = pass', 'toolAccessStatus', '', 'pass',
   '', 'reserved', '', 'admin', SYSDATE())
ON DUPLICATE KEY UPDATE
  discipline = VALUES(discipline),
  discipline_name = VALUES(discipline_name),
  item_type = VALUES(item_type),
  item_name = VALUES(item_name),
  direction = VALUES(direction),
  default_weight = VALUES(default_weight),
  default_limit_value = VALUES(default_limit_value),
  unit = VALUES(unit),
  sort_order = VALUES(sort_order),
  status = VALUES(status),
  remark = VALUES(remark),
  rule_type = VALUES(rule_type),
  rule_expression = VALUES(rule_expression),
  target_field = VALUES(target_field),
  reference_field = VALUES(reference_field),
  operator_code = VALUES(operator_code),
  threshold_value = VALUES(threshold_value),
  execute_mode = VALUES(execute_mode),
  rule_payload = VALUES(rule_payload),
  update_by = 'admin',
  update_time = SYSDATE();

UPDATE t2_design_variable_catalog
SET status = '1',
    update_by = 'admin',
    update_time = SYSDATE()
WHERE variable_code NOT IN (
  'PIPE_L1', 'PIPE_L2', 'PIPE_BEND_RADIUS', 'PIPE_THETA_1', 'PIPE_THETA_2',
  'CABLE_ROUTE_SIDE', 'CABLE_PIPE_CLEARANCE', 'CABLE_OFFSET',
  'CABLE_BEND_RADIUS', 'CLAMP_SPACING', 'SERVICE_MARGIN'
);

INSERT INTO t2_design_variable_catalog
  (discipline, discipline_name, subtask_code, variable_code, variable_name, variable_type,
   default_value, lower_bound, upper_bound, step_value, unit, sort_order, status, remark, create_by, create_time)
VALUES
  ('hydraulic', '液压工程师', 'hydraulic_impact', 'PIPE_L1', 'L1 第一段直管长度', 'continuous', '300', '50', '550', '1', 'mm', 10, '0', '液压弯管抗冲击优化变量', 'admin', SYSDATE()),
  ('hydraulic', '液压工程师', 'hydraulic_impact', 'PIPE_L2', 'L2 第二段直管长度', 'continuous', '150', '50', '300', '1', 'mm', 20, '0', '液压弯管抗冲击优化变量', 'admin', SYSDATE()),
  ('hydraulic', '液压工程师', 'hydraulic_impact', 'PIPE_BEND_RADIUS', 'R 两处弯管圆角半径', 'continuous', '30', '20', '80', '1', 'mm', 30, '0', '液压弯管抗冲击优化变量', 'admin', SYSDATE()),
  ('hydraulic', '液压工程师', 'hydraulic_impact', 'PIPE_THETA_1', 'θ1 第一个弯角弯曲角度', 'continuous', '110', '30', '150', '1', 'deg', 40, '0', '液压弯管抗冲击优化变量', 'admin', SYSDATE()),
  ('hydraulic', '液压工程师', 'hydraulic_impact', 'PIPE_THETA_2', 'θ2 第二个弯角弯曲角度', 'continuous', '120', '30', '150', '1', 'deg', 50, '0', '液压弯管抗冲击优化变量', 'admin', SYSDATE()),
  ('layout', '布局工程师', 'cable_pipe_layout', 'CABLE_ROUTE_SIDE', '线缆布置侧别', 'enum', 'upper', 'upper', 'outer', '', '', 60, '0', '预留布局策略字段：upper/lower/inner/outer', 'admin', SYSDATE()),
  ('layout', '布局工程师', 'cable_pipe_layout', 'CABLE_PIPE_CLEARANCE', '线缆与液压管最小隔离距离', 'continuous', '40', '20', '80', '1', 'mm', 70, '0', '预留最小距离校核字段', 'admin', SYSDATE()),
  ('layout', '布局工程师', 'cable_pipe_layout', 'CABLE_OFFSET', '线缆相对液压管中心线偏移距离', 'continuous', '60', '30', '120', '1', 'mm', 80, '0', '预留路径偏移字段', 'admin', SYSDATE()),
  ('layout', '布局工程师', 'cable_pipe_layout', 'CABLE_BEND_RADIUS', '线缆最小弯曲半径', 'continuous', '50', '30', '120', '1', 'mm', 90, '0', '预留弯曲半径校核字段', 'admin', SYSDATE()),
  ('layout', '布局工程师', 'cable_pipe_layout', 'CLAMP_SPACING', '线夹/管夹布置间距', 'continuous', '180', '100', '250', '5', 'mm', 100, '0', '预留线夹间距校核字段', 'admin', SYSDATE()),
  ('layout', '布局工程师', 'cable_pipe_layout', 'SERVICE_MARGIN', '检修操作预留空间', 'continuous', '40', '30', '100', '1', 'mm', 110, '0', '预留检修空间校核字段', 'admin', SYSDATE())
ON DUPLICATE KEY UPDATE
  discipline = VALUES(discipline),
  discipline_name = VALUES(discipline_name),
  subtask_code = VALUES(subtask_code),
  variable_name = VALUES(variable_name),
  variable_type = VALUES(variable_type),
  default_value = VALUES(default_value),
  lower_bound = VALUES(lower_bound),
  upper_bound = VALUES(upper_bound),
  step_value = VALUES(step_value),
  unit = VALUES(unit),
  sort_order = VALUES(sort_order),
  status = VALUES(status),
  remark = VALUES(remark),
  update_by = 'admin',
  update_time = SYSDATE();
